name: CanadaTaxBrackets
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - attrs=21.2.0
  - black=19.10b0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - click=8.0.1
  - importlib-metadata=4.8.1
  - kaleido-core=0.2.1
  - libcxx=12.0.0
  - libffi=3.3
  - mathjax=2.7.7
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - openssl=1.1.1l
  - pathspec=0.7.0
  - pip=21.2.4
  - plotly=5.1.0
  - python=3.9.7
  - python-kaleido=0.2.1
  - python_abi=3.9
  - readline=8.1
  - regex=2021.8.3
  - setuptools=58.0.4
  - six=1.15.0
  - sqlite=3.36.0
  - tenacity=8.0.1
  - tk=8.6.10
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
